image: node:23.3.0-alpine3.20

stages:
  - build

pages:
  stage: build
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm run build
  artifacts:
    paths:
      - out
  publish: out
  only:
    - main
